export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_DISHES = 'ADD_DISHES';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_PROMOS = 'ADD_PROMOS';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const DISHES_LOADING = 'DISHES_LOADING';
export const PROMOS_LOADING = 'PROMOS_LOADING';

export const DISHES_FAILED = 'DISHES_FAILED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const FETCH_DISHES = 'FETCH_DISHES';
export const FETCH_LEADERS = 'FETCH_LEADERS';
export const FETCH_PROMOS = 'FETCH_PROMOS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
